### jsp ###
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
### database ###
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board_chat
    username: boardchat
    password: passw0rd


### spring boot reload ###
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    remote:
      restart:
        enabled: true
### JPA info ###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


